
name: Build Image
on:
  push:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        env:
          GIT_TAG: v0.0.1
        run: |
          echo "Building image with version $GIT_TAG"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/spring-test:v0.0.1
          echo "Image with version $GIT_TAG has been successfully built, pushing to registry"
          docker push ${{ secrets.DOCKER_USER }}/spring-test:v0.0.1
